[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd api && npm install"]

[phases.build]
cmds = ["cd api && npx prisma generate && npm run build"]

[start]
cmd = "cd api && npm run start"
